export const images = {
  loginPage: require("../assets/images/login.png"),
  googleIcon: require("../assets/images/googleIcon.svg").default,
  facebookIcon: require("../assets/images/facebookIcon.svg"),
  registerPage: require("../assets/images/register.png"),
  searchIcon: require("../assets/images/searchIcon.svg"),
  userAvatar: require("../assets/images/userAvatar.jpg"),
  arrowDown: require("../assets/images/arrow-down.svg"),
  posterImage: require("../assets/images/posterImage.png"),
  disney: require("../assets/images/disney.png"),
  nationalgeographic: require("../assets/images/nationalgeographic.png"),
  starWars: require("../assets/images/starwars.png"),
  marvel: require("../assets/images/marvel.png"),
  moviePosterOne: require("../assets/images/MoviePoster/moviePoster.png"),
  moviePosterTwo: require("../assets/images/MoviePoster/moviePoster2.png"),
  moviePosterThree: require("../assets/images/MoviePoster/moviePoster3.png"),
  filmroll: require("../assets/images/filmroll.png"),
  star: require("../assets/images/star.png"),
  continueWatching: require("../assets/images/MoviePoster/continueWatching.png"),
  continueWatching2: require("../assets/images/MoviePoster/continueWatching2.png"),
};
